/*
	작성자: 윤정도
	생성일: 2026-09-12
	=====
	설명: @scouter/gui 패키지 진입점. Core(04)를 공개한다.
*/

export const GuiVersion = "0.4.0";

export { UIElement } from "./Core/UIElement";
export { UIProperty } from "./Core/UIProperty";
export type { IUIPropertyMeta } from "./Core/UIProperty";
export { RoutedEvent, RoutedEventArgs, RoutingStrategy, PointerEventArgs, KeyEventArgs, WheelEventArgs, ValueChangedEventArgs, PropertyChangedEventArgs, SizeChangedEventArgs } from "./Core/RoutedEvent";
export { ElementRegistry } from "./Core/ElementRegistry";
export { SizeObserver } from "./Core/SizeObserver";
export { InputDispatcher } from "./Core/InputDispatcher";
export { Gui } from "./Core/Gui";
export { Thickness } from "./Core/Thickness";
export { Visibility, HAlign, VAlign, Orientation, Dock } from "./Core/UITypes";
export type { IPoint, ISize } from "./Core/UITypes";
export type { IDisposable } from "./Core/Disposable";
export { DisposableBag } from "./Core/Disposable";
export { SimpleEvent } from "./Core/SimpleEvent";

import "./Panels/RegisterPanels";
import "./Host/RegisterHost";
import "./Xml/RegisterXml";
import "./Controls/RegisterControls";
import "./Controls/Items/RegisterItems";
import "./Theme/RegisterTheme";
export { Grid } from "./Panels/Grid";
export { StackPanel } from "./Panels/StackPanel";
export { DockPanel } from "./Panels/DockPanel";
export { WrapPanel } from "./Panels/WrapPanel";
export { Canvas } from "./Panels/Canvas";
export { UniformGrid } from "./Panels/UniformGrid";
export { Border } from "./Panels/Border";
export { ScrollViewer, ScrollBarVisibility } from "./Panels/ScrollViewer";
export { Viewbox, Stretch } from "./Panels/Viewbox";
export { GridSplitter, ResizeDirection } from "./Panels/GridSplitter";
export { Panel } from "./Panels/Panel";
export { Decorator } from "./Panels/Decorator";
export { AttachedProperty } from "./Panels/AttachedProperty";
export type { IAttachedMeta } from "./Panels/AttachedProperty";
export { GridLength, GridUnitType, RowDefinition, ColumnDefinition, DefinitionCollection } from "./Panels/GridDefinitions";
export { Control } from "./Controls/Control";
export { ContentControl } from "./Controls/ContentControl";
export { ContentPresenter } from "./Controls/ContentPresenter";
export { Window, ClosingEventArgs } from "./Host/Window";
export { UserControl } from "./Host/UserControl";
export { UIManager, ToastKind } from "./Host/UIManager";
export type { IToastOptions } from "./Host/UIManager";
export { UILayer, UILayerKind } from "./Host/UILayer";
export { WindowRegistry } from "./Host/WindowRegistry";
export type { WindowCtor } from "./Host/WindowRegistry";
export { RegisterWindow } from "./Host/RegisterWindow";
export { MapLayoutProvider } from "./Host/MapLayoutProvider";
export type { ILayoutProvider } from "./Host/ILayoutProvider";
export type { INavigationService } from "./Host/INavigationService";
export { DataList, DataType } from "./Xml/DataList";
export { UIValues, UIValueKind } from "./Xml/UIValue";
export type { UIValue } from "./Xml/UIValue";
export { XmlLoader } from "./Xml/XmlLoader";
export type { ILoadResult } from "./Xml/XmlLoader";
export { ElementCatalog } from "./Xml/ElementCatalog";
export { AttributeApplier } from "./Xml/AttributeApplier";
export { Binding } from "./Xml/Binding";
export { BindingGraph } from "./Xml/BindingGraph";
export { BindingResolver } from "./Xml/BindingResolver";
export type { IBindingScope } from "./Xml/BindingResolver";
export { ExpressionParser } from "./Xml/Expression/Parser";
export { Lexer, TokenKind } from "./Xml/Expression/Lexer";
export type { IToken } from "./Xml/Expression/Lexer";
export { BindingMode, AstRefs } from "./Xml/Expression/Ast";
export type { AstNode, IParsedBinding, RefNode } from "./Xml/Expression/Ast";
export { LoadContext } from "./Xml/LoadContext";
export type { ISettingsSource, IThemeSource, ICommandSource, IPendingBinding, ILintMessage } from "./Xml/LoadContext";
export { LayoutLint } from "./Xml/LayoutLint";
export { HotReloader } from "./Xml/HotReloader";
export type { IFileWatcher } from "./Xml/HotReloader";
export { ButtonBase, ClickMode } from "./Controls/ButtonBase";
export { Button } from "./Controls/Button";
export { RepeatButton } from "./Controls/RepeatButton";
export { ToggleButton } from "./Controls/ToggleButton";
export { CheckBox } from "./Controls/CheckBox";
export { RadioButton } from "./Controls/RadioButton";
export { RadioGroupScope } from "./Controls/RadioGroupScope";
export { TextBlock } from "./Controls/TextBlock";
export { TextBox } from "./Controls/TextBox";
export { PasswordBox } from "./Controls/PasswordBox";
export { Label } from "./Controls/Label";
export { RangeBase, ProgressBar, Slider, NumericUpDown } from "./Controls/Range";
export { Image } from "./Controls/Image";
export { Icon } from "./Controls/Icon";
export { VirtualList } from "./Controls/Scouter/VirtualList";
export { RingBuffer } from "./Controls/Scouter/RingBuffer";
export { LogView } from "./Controls/Scouter/LogView";
export type { ILogEntry, LogLevel } from "./Controls/Scouter/LogView";
export { Badge } from "./Controls/Scouter/Badge";
export { PropertyGrid, EditorFactory } from "./Controls/Scouter/PropertyGrid";
export type { IJsonSchemaNode, IPropertyEditor } from "./Controls/Scouter/PropertyGrid";
export { Separator } from "./Controls/Separator";
export { RegisterElement } from "./Controls/RegisterElement";
export { TitleBar } from "./Controls/Scouter/TitleBar";
export type { IWindowChrome } from "./Controls/Scouter/IWindowChrome";
export { StatusBar, StatusBarItem } from "./Controls/Scouter/StatusBar";
export { StatusDot, DotStatus } from "./Controls/Scouter/StatusDot";
export { Spinner } from "./Controls/Scouter/Spinner";
export { Avatar } from "./Controls/Scouter/Avatar";
export { CodeEditor } from "./Controls/Scouter/CodeEditor";
export type { IEditorMarker } from "./Controls/Scouter/CodeEditor";
export { DiffView } from "./Controls/Scouter/DiffView";
export { MarkdownView, LinkEventArgs } from "./Controls/Scouter/MarkdownView";
export { MonacoLoader } from "./Controls/Scouter/MonacoLoader";
export { MonacoTheme } from "./Controls/Scouter/MonacoTheme";
export { ToastService } from "./Controls/Scouter/ToastService";
export type { ToastHandle } from "./Controls/Scouter/ToastService";
export { SelectionModel } from "./Controls/Items/SelectionModel";
export type { ISelectionDiff } from "./Controls/Items/SelectionModel";
export { ItemContainerGenerator, ItemsControl } from "./Controls/Items/ItemsControl";
export { Selector, SelectionMode, SelectionSource, SelectionChangedEventArgs } from "./Controls/Items/Selector";
export { ListBox, ListBoxItem } from "./Controls/Items/ListBox";
export { ComboBox } from "./Controls/Items/ComboBox";
export { TabControl, TabItem } from "./Controls/Items/TabControl";
export { ListView, GridView, GridViewColumn, GridViewHeaderArgs } from "./Controls/Items/ListView";
export type { IGridViewColumnDef } from "./Controls/Items/ListView";
export { Popup, PopupPlacer } from "./Controls/Items/Popup";
export type { PlacementKind, IPlacementRect } from "./Controls/Items/Popup";
export { ToolTipService } from "./Controls/Items/ToolTipService";
export { Expander, GroupBox } from "./Controls/Items/Expander";
export { TreeView, TreeViewItem } from "./Controls/Items/TreeView";
export type { ITreeAdapter, ITreeRow } from "./Controls/Items/TreeView";
export { MenuBase, Menu, MenuItem } from "./Controls/Items/Menu";
export { ContextMenu } from "./Controls/Items/ContextMenu";
export { ToolBar } from "./Controls/Items/ToolBar";
export { DataGrid } from "./Controls/Items/DataGrid";
export { kCoreTokens } from "./Theme/Theme";
export type { ITheme, IResolvedTheme, IThemeJson, ITypography, ThemeScheme, ThemeMode, ThemeSource, DensityKind } from "./Theme/Theme";
export { ThemeResolver } from "./Theme/ThemeResolver";
export { ThemeCss } from "./Theme/ThemeCss";
export { ThemeLint } from "./Theme/ThemeLint";
export type { IThemeLintMessage, IThemeLintResult } from "./Theme/ThemeLint";
export { Color } from "./Theme/Color";
export type { IRgb } from "./Theme/Color";
